// <auto-generated />
using System;
using ConstructionManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructionManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129233200_AddTenantIdToUser")]
    partial class AddTenantIdToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinalApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectApprovalRuleId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("FinalApprovedByUserId");

                    b.HasIndex("ProjectApprovalRuleId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("ApproverUserId");

                    b.ToTable("ApprovalSteps");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQExecutedDelta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeltaDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeltaQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("BOQExecutedDeltas");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BOQItems");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItemNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedMediaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisibleToRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RelatedMediaId");

                    b.ToTable("BOQItemNotes");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQMeasured", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("AgreedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExecutedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BOQMeasured");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQProfitabilityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProfitPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.ToTable("BOQProfitabilityLogs");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQSupervision", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BaseCalculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CustomBaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SupervisionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BOQSupervision");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ClientPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ClientPayments");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DelayGracePeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("DelayNotificationIntervalDays")
                        .HasColumnType("int");

                    b.Property<bool>("DelayNotificationIsOneTimeOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("DelayNotificationSendEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableDelayNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableInvoiceAggregation")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableInvoiceReview")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePhotoUpload")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxPhotosPerUpload")
                        .HasColumnType("int");

                    b.Property<string>("PhotoApproverRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequirePhotoReview")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.EscalationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SentByEmail")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("EscalationLogs");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.InvoiceSequence", b =>
                {
                    b.Property<int>("YearPart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YearPart");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YearPart"));

                    b.Property<int>("NextNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("YearPart");

                    b.ToTable("InvoiceSequences", (string)null);
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ItemDailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ClosingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DailyProgressPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgressNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("BOQItemId", "LogDate")
                        .IsUnique();

                    b.ToTable("ItemDailyLogs");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ItemInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("RetentionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RetentionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierVendor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ItemInvoice_InvoiceNumber_Unique");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("ItemInvoices");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeneralManagerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.Property<int?>("UserId2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("GeneralManagerUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectApprovalRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ResponseTimeoutHours")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploaderRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectApprovalRules");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectRoles");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRolePermission", b =>
                {
                    b.Property<int>("ProjectRoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("ProjectRoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ProjectRolePermissions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelayGracePeriodDays")
                        .HasColumnType("int");

                    b.Property<int?>("DelayNotificationIntervalDays")
                        .HasColumnType("int");

                    b.Property<bool?>("DelayNotificationIsOneTimeOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("DelayNotificationSendEmail")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnableDelayNotification")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnableInvoiceAggregation")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnableInvoiceReview")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnablePhotoUpload")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxPhotosPerUpload")
                        .HasColumnType("int");

                    b.Property<string>("PhotoApproverRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequirePhotoReview")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProjectSettings");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ReportsToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportsToUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectTeamMembers");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamRole", b =>
                {
                    b.Property<int>("ProjectTeamMemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectTeamMemberId", "ProjectRoleId");

                    b.HasIndex("ProjectRoleId");

                    b.ToTable("ProjectTeamRoles");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.SiteMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewerUserId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploaderUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("UploaderUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("SiteMedias");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAIAssistance")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowAdvancedReports")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowCustomBranding")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBOQItems")
                        .HasColumnType("int");

                    b.Property<int>("MaxDailyPhotos")
                        .HasColumnType("int");

                    b.Property<int>("MaxTeamMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany()
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "FinalApprovedBy")
                        .WithMany()
                        .HasForeignKey("FinalApprovedByUserId");

                    b.HasOne("ConstructionManagement.Domain.Entities.ProjectApprovalRule", "ApprovalRule")
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("ProjectApprovalRuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalRule");

                    b.Navigation("BOQItem");

                    b.Navigation("FinalApprovedBy");

                    b.Navigation("Project");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ApprovalStep", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.ApprovalRequest", "Request")
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId");

                    b.Navigation("ApproverUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQExecutedDelta", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany()
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOQItem");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItem", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("BOQItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItemNote", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("Notes")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("Notes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.SiteMedia", "RelatedMedia")
                        .WithMany("RelatedNotes")
                        .HasForeignKey("RelatedMediaId");

                    b.Navigation("BOQItem");

                    b.Navigation("Creator");

                    b.Navigation("Project");

                    b.Navigation("RelatedMedia");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQMeasured", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "Item")
                        .WithOne("MeasuredData")
                        .HasForeignKey("ConstructionManagement.Domain.Entities.BOQMeasured", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQProfitabilityLog", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("ProfitabilityLogs")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOQItem");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQSupervision", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "Item")
                        .WithOne("SupervisionData")
                        .HasForeignKey("ConstructionManagement.Domain.Entities.BOQSupervision", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ClientPayment", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("ClientPayments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.EscalationLog", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("EscalationLogs")
                        .HasForeignKey("BOQItemId");

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("EscalationLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Recipient")
                        .WithMany("ReceivedEscalations")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOQItem");

                    b.Navigation("Project");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ItemDailyLog", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("DailyLogs")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("ClosedDailyLogs")
                        .HasForeignKey("UserId");

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("CreatedDailyLogs")
                        .HasForeignKey("UserId1");

                    b.Navigation("BOQItem");

                    b.Navigation("ClosedByUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ItemInvoice", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("Invoices")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("ItemInvoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("CreatedInvoices")
                        .HasForeignKey("UserId");

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("ReviewedInvoices")
                        .HasForeignKey("UserId1");

                    b.Navigation("BOQItem");

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Project", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ClosedBy")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "GeneralManager")
                        .WithMany()
                        .HasForeignKey("GeneralManagerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Package", "Package")
                        .WithMany("Projects")
                        .HasForeignKey("PackageId");

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("ClosedProjects")
                        .HasForeignKey("UserId");

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("ManagedProjects")
                        .HasForeignKey("UserId1");

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("OwnedProjects")
                        .HasForeignKey("UserId2");

                    b.Navigation("ClosedBy");

                    b.Navigation("GeneralManager");

                    b.Navigation("Owner");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectApprovalRule", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany()
                        .HasForeignKey("BOQItemId");

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOQItem");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRole", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRolePermission", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Permission", "Permission")
                        .WithMany("ProjectRolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.ProjectRole", "ProjectRole")
                        .WithMany("Permissions")
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("ProjectRole");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectSettings", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithOne("Settings")
                        .HasForeignKey("ConstructionManagement.Domain.Entities.ProjectSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ReportsTo")
                        .WithMany("Subordinates")
                        .HasForeignKey("ReportsToUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ReportsTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamRole", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.ProjectRole", "ProjectRole")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.ProjectTeamMember", "ProjectTeamMember")
                        .WithMany("ProjectTeamRoles")
                        .HasForeignKey("ProjectTeamMemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectRole");

                    b.Navigation("ProjectTeamMember");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.SiteMedia", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("SiteMedias")
                        .HasForeignKey("BOQItemId");

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("SiteMedias")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("ReviewedMedias")
                        .HasForeignKey("UserId");

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("UploadedMedias")
                        .HasForeignKey("UserId1");

                    b.Navigation("BOQItem");

                    b.Navigation("Project");

                    b.Navigation("Reviewer");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany()
                        .HasForeignKey("BOQItemId");

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("Transactions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("CreatedTransactions")
                        .HasForeignKey("UserId");

                    b.HasOne("ConstructionManagement.Domain.Entities.User", null)
                        .WithMany("ReviewedTransactions")
                        .HasForeignKey("UserId1");

                    b.Navigation("BOQItem");

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItem", b =>
                {
                    b.Navigation("DailyLogs");

                    b.Navigation("EscalationLogs");

                    b.Navigation("Invoices");

                    b.Navigation("MeasuredData");

                    b.Navigation("Notes");

                    b.Navigation("ProfitabilityLogs");

                    b.Navigation("SiteMedias");

                    b.Navigation("SupervisionData");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Permission", b =>
                {
                    b.Navigation("ProjectRolePermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Project", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("BOQItems");

                    b.Navigation("ClientPayments");

                    b.Navigation("EscalationLogs");

                    b.Navigation("ItemInvoices");

                    b.Navigation("Notes");

                    b.Navigation("ProjectRoles");

                    b.Navigation("Settings");

                    b.Navigation("SiteMedias");

                    b.Navigation("TeamMembers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectApprovalRule", b =>
                {
                    b.Navigation("ApprovalRequests");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRole", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.Navigation("ProjectTeamRoles");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.SiteMedia", b =>
                {
                    b.Navigation("RelatedNotes");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("ClosedDailyLogs");

                    b.Navigation("ClosedProjects");

                    b.Navigation("CreatedDailyLogs");

                    b.Navigation("CreatedInvoices");

                    b.Navigation("CreatedTransactions");

                    b.Navigation("ManagedProjects");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedProjects");

                    b.Navigation("ProjectMemberships");

                    b.Navigation("ReceivedEscalations");

                    b.Navigation("ReviewedInvoices");

                    b.Navigation("ReviewedMedias");

                    b.Navigation("ReviewedTransactions");

                    b.Navigation("Subordinates");

                    b.Navigation("UploadedMedias");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
