// <auto-generated />
using System;
using ConstructionManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructionManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220231800_AddLeaveManagement")]
    partial class AddLeaveManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // LeaveType entity
            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveType", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("AllowCarryOver")
                    .HasColumnType("bit");

                b.Property<string>("ColorCode")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<int?>("CompanyId")
                    .HasColumnType("int");

                b.Property<int>("DefaultDaysPerYear")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("IsPaid")
                    .HasColumnType("bit");

                b.Property<int>("MaxCarryOverDays")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("RequiresApproval")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("CompanyId");

                b.ToTable("LeaveTypes");
            });

            // LeaveBalance entity
            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveBalance", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal>("CarriedOver")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("LeaveTypeId")
                    .HasColumnType("int");

                b.Property<decimal>("PendingDays")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("TotalAllocated")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("UsedDays")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.Property<int>("Year")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("LeaveTypeId");

                b.HasIndex("UserId");

                b.HasIndex("UserId", "LeaveTypeId", "Year")
                    .IsUnique();

                b.ToTable("LeaveBalances");
            });

            // LeaveRequest entity
            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("ApprovedByUserId")
                    .HasColumnType("int");

                b.Property<DateTime?>("ApprovedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("ApproverComments")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<int>("LeaveTypeId")
                    .HasColumnType("int");

                b.Property<string>("Reason")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("RejectionReason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<decimal>("TotalDays")
                    .HasColumnType("decimal(18,2)");

                b.Property<bool>("UserNotified")
                    .HasColumnType("bit");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ApprovedByUserId");

                b.HasIndex("LeaveTypeId");

                b.HasIndex("UserId");

                b.ToTable("LeaveRequests");
            });

            // LeaveRequestAttachment entity
            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveRequestAttachment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ContentType")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<long>("FileSize")
                    .HasColumnType("bigint");

                b.Property<int>("LeaveRequestId")
                    .HasColumnType("int");

                b.Property<DateTime>("UploadedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("LeaveRequestId");

                b.ToTable("LeaveRequestAttachments");
            });

            // Holiday entity
            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Holiday", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("CompanyId")
                    .HasColumnType("int");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsRecurring")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("CompanyId");

                b.ToTable("Holidays");
            });

            // Foreign Keys
            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveBalance", b =>
            {
                b.HasOne("ConstructionManagement.Domain.Entities.LeaveType", "LeaveType")
                    .WithMany()
                    .HasForeignKey("LeaveTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ConstructionManagement.Domain.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LeaveType");

                b.Navigation("User");
            });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveRequest", b =>
            {
                b.HasOne("ConstructionManagement.Domain.Entities.User", "ApprovedBy")
                    .WithMany()
                    .HasForeignKey("ApprovedByUserId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("ConstructionManagement.Domain.Entities.LeaveType", "LeaveType")
                    .WithMany()
                    .HasForeignKey("LeaveTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ConstructionManagement.Domain.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ApprovedBy");

                b.Navigation("LeaveType");

                b.Navigation("User");
            });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveRequestAttachment", b =>
            {
                b.HasOne("ConstructionManagement.Domain.Entities.LeaveRequest", "LeaveRequest")
                    .WithMany("Attachments")
                    .HasForeignKey("LeaveRequestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LeaveRequest");
            });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Holiday", b =>
            {
                b.HasOne("ConstructionManagement.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveType", b =>
            {
                b.HasOne("ConstructionManagement.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.LeaveRequest", b =>
            {
                b.Navigation("Attachments");
            });
#pragma warning restore 612, 618
        }
    }
}
