// <auto-generated />
using System;
using ConstructionManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructionManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122235048_InitialWithSeed_Fixed")]
    partial class InitialWithSeed_Fixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BOQItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountingType = "Measured",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemCode = "A-01",
                            ItemName = "حفر أساسات",
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "جاري",
                            Unit = "م³"
                        },
                        new
                        {
                            Id = 2,
                            AccountingType = "Measured",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemCode = "B-02",
                            ItemName = "صب خرسانة أساسات",
                            ProjectId = 1,
                            Status = "جديد",
                            Unit = "م³"
                        },
                        new
                        {
                            Id = 3,
                            AccountingType = "Supervision",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemCode = "C-01",
                            ItemName = "إشراف عام",
                            ProjectId = 1,
                            Status = "جاري"
                        },
                        new
                        {
                            Id = 4,
                            AccountingType = "Measured",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemCode = "X-01",
                            ItemName = "بناء هيكل",
                            ProjectId = 2,
                            Status = "جاري",
                            Unit = "م²"
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItemNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedMediaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisibleToRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RelatedMediaId");

                    b.ToTable("BOQItemNotes");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQMeasured", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("AgreedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExecutedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BOQMeasured");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgreedQuantity = 1200m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExecutedQuantity = 600m,
                            UnitPrice = 450m
                        },
                        new
                        {
                            Id = 2,
                            AgreedQuantity = 800m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExecutedQuantity = 0m,
                            UnitPrice = 1850m
                        },
                        new
                        {
                            Id = 4,
                            AgreedQuantity = 5000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExecutedQuantity = 1200m,
                            UnitPrice = 320m
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQProfitabilityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProfitPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.ToTable("BOQProfitabilityLogs");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQSupervision", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BaseCalculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CustomBaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SupervisionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BOQSupervision");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            BaseCalculation = "AllProjectInvoices",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedTotalCost = 1020000m,
                            SupervisionPercentage = 8.5m
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ClientPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ClientPayments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2000000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsConfirmed = true,
                            PaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000000m,
                            CreatedAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsConfirmed = false,
                            PaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DelayGracePeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("DelayNotificationIntervalDays")
                        .HasColumnType("int");

                    b.Property<bool>("DelayNotificationIsOneTimeOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("DelayNotificationSendEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableDelayNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableInvoiceAggregation")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableInvoiceReview")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePhotoUpload")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxPhotosPerUpload")
                        .HasColumnType("int");

                    b.Property<string>("PhotoApproverRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequirePhotoReview")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CompanySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelayGracePeriodDays = 5,
                            DelayNotificationIntervalDays = 7,
                            DelayNotificationIsOneTimeOnly = false,
                            DelayNotificationSendEmail = true,
                            EnableDelayNotification = true,
                            EnableInvoiceAggregation = true,
                            EnableInvoiceReview = true,
                            EnablePhotoUpload = true,
                            MaxPhotosPerUpload = 15,
                            PhotoApproverRole = "مراجع فني",
                            RequirePhotoReview = true
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.EscalationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SentByEmail")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("EscalationLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BOQItemId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EscalationType = "ItemStartDelay",
                            Message = "",
                            ProjectId = 1,
                            RecipientUserId = 3,
                            SentAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            SentByEmail = false
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ItemDailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ClosingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DailyProgressPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgressNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("BOQItemId", "LogDate")
                        .IsUnique();

                    b.ToTable("ItemDailyLogs");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ItemInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierVendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("ItemInvoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 120000m,
                            BOQItemId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 300000m,
                            BOQItemId = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            ReviewerUserId = 5,
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "البند B-02 متأخر",
                            Priority = 1,
                            Title = "تحذير تأخير",
                            Type = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "صورة/فيديو جديد يحتاج مراجعة",
                            Priority = 1,
                            Title = "مراجعة وسائط",
                            Type = 8,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "تعديل بيانات المشروع",
                            Name = "Project.Edit"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "إغلاق/إنهاء المشروع",
                            Name = "Project.Close"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "عرض الملخص المالي",
                            Name = "Financials.View"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "إضافة معاملة مالية",
                            Name = "Transaction.Add"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مراجعة/اعتماد المعاملات",
                            Name = "Transaction.Review"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مراجعة الصور والفيديوهات",
                            Name = "Media.Review"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "إغلاق السجل اليومي",
                            Name = "DailyLog.Close"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "اعتماد الفواتير",
                            Name = "Invoice.Approve"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "تعديل إعدادات المشروع",
                            Name = "Settings.Manage"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "إدارة المستخدمين (عالمي)",
                            Name = "Users.Manage"
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeneralManagerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("GeneralManagerUserId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountingSystem = "Mixed",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مشروع سكني لاختبار كامل النظام",
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            GeneralManagerUserId = 3,
                            IsClosed = false,
                            OwnerUserId = 1,
                            ProjectName = "فيلا القاهرة الجديدة – التجريبي",
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "جاري",
                            TotalContractValue = 12000000m
                        },
                        new
                        {
                            Id = 2,
                            AccountingSystem = "Measured",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مشروع تجاري لاختبار تعدد المشاريع",
                            GeneralManagerUserId = 6,
                            IsClosed = false,
                            OwnerUserId = 2,
                            ProjectName = "مبنى إداري – مدينة نصر",
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "جديد",
                            TotalContractValue = 8500000m
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectApprovalRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ResponseTimeoutHours")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploaderRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectApprovalRules");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "كل الصلاحيات",
                            Name = "مدير المشروع",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "رفع وسجل يومي",
                            Name = "مهندس ميداني",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مراجعة فقط",
                            Name = "مراجع فني",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "كل الصلاحيات",
                            Name = "مدير المشروع 2",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "إدارة معاملات وفواتير",
                            Name = "محاسب",
                            ProjectId = 2
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRolePermission", b =>
                {
                    b.Property<int>("ProjectRoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("ProjectRoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ProjectRolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            ProjectRoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            ProjectRoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            ProjectRoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            ProjectRoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            ProjectRoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            ProjectRoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            ProjectRoleId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 2
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 4
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 6
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 8
                        },
                        new
                        {
                            ProjectRoleId = 4,
                            PermissionId = 9
                        },
                        new
                        {
                            ProjectRoleId = 5,
                            PermissionId = 3
                        },
                        new
                        {
                            ProjectRoleId = 5,
                            PermissionId = 4
                        },
                        new
                        {
                            ProjectRoleId = 5,
                            PermissionId = 5
                        },
                        new
                        {
                            ProjectRoleId = 5,
                            PermissionId = 8
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelayGracePeriodDays")
                        .HasColumnType("int");

                    b.Property<int?>("DelayNotificationIntervalDays")
                        .HasColumnType("int");

                    b.Property<bool?>("DelayNotificationIsOneTimeOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("DelayNotificationSendEmail")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnableDelayNotification")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnableInvoiceAggregation")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnableInvoiceReview")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnablePhotoUpload")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxPhotosPerUpload")
                        .HasColumnType("int");

                    b.Property<string>("PhotoApproverRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequirePhotoReview")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProjectSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelayNotificationIntervalDays = 5,
                            EnableDelayNotification = true,
                            MaxPhotosPerUpload = 20,
                            PhotoApproverRole = "مراجع فني",
                            RequirePhotoReview = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnableDelayNotification = false,
                            EnablePhotoUpload = true,
                            RequirePhotoReview = false
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ReportsToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportsToUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectTeam");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 1,
                            ReportsToUserId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 1,
                            ReportsToUserId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 2,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamRole", b =>
                {
                    b.Property<int>("ProjectTeamMemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectTeamMemberId", "ProjectRoleId");

                    b.HasIndex("ProjectRoleId");

                    b.ToTable("ProjectTeamRoles");

                    b.HasData(
                        new
                        {
                            ProjectTeamMemberId = 1,
                            ProjectRoleId = 1,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0
                        },
                        new
                        {
                            ProjectTeamMemberId = 2,
                            ProjectRoleId = 2,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0
                        },
                        new
                        {
                            ProjectTeamMemberId = 3,
                            ProjectRoleId = 3,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0
                        },
                        new
                        {
                            ProjectTeamMemberId = 4,
                            ProjectRoleId = 4,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مدير النظام الكلي – كل الصلاحيات",
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مدير الشركة – إدارة مستخدمين ومشاريع",
                            Name = "CompanyAdmin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مشاهد فقط – لا تعديل",
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.SiteMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewerUserId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploaderUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("UploaderUserId");

                    b.ToTable("SiteMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BOQItemId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "",
                            IsApproved = false,
                            MediaType = "Photo",
                            ProjectId = 1,
                            Source = 0,
                            Status = "Pending",
                            UploaderUserId = 4
                        },
                        new
                        {
                            Id = 2,
                            BOQItemId = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "",
                            IsApproved = false,
                            MediaType = "Video",
                            ProjectId = 1,
                            ReviewerUserId = 5,
                            Source = 0,
                            Status = "Approved",
                            UploaderUserId = 4
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BOQItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BOQItemId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150000m,
                            BOQItemId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 4,
                            ProjectId = 1,
                            Status = 1,
                            TransactionDate = new DateTime(2026, 1, 22, 23, 50, 47, 846, DateTimeKind.Utc).AddTicks(1713),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 80000m,
                            BOQItemId = 1,
                            CreatedAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 4,
                            ProjectId = 1,
                            Status = 0,
                            TransactionDate = new DateTime(2026, 1, 22, 23, 50, 47, 846, DateTimeKind.Utc).AddTicks(2273),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 400000m,
                            BOQItemId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 6,
                            ProjectId = 2,
                            Status = 1,
                            TransactionDate = new DateTime(2026, 1, 22, 23, 50, 47, 846, DateTimeKind.Utc).AddTicks(2275),
                            Type = 0
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "super@company.com",
                            FullName = "Super Admin",
                            PasswordHash = "hashed_super123"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@company.com",
                            FullName = "Company Admin",
                            PasswordHash = "hashed_admin123"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed.pm1@demo.com",
                            FullName = "Ahmed – Project Manager 1",
                            PasswordHash = "hashed_pm123"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohamed.engineer@demo.com",
                            FullName = "Mohamed – Site Engineer",
                            PasswordHash = "hashed_eng123"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.reviewer@demo.com",
                            FullName = "Sara – Financial Reviewer",
                            PasswordHash = "hashed_rev123"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pm2@demo.com",
                            FullName = "Project Manager 2",
                            PasswordHash = "hashed_pm223"
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItem", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("BOQItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItemNote", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("Notes")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("Notes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.SiteMedia", "RelatedMedia")
                        .WithMany("RelatedNotes")
                        .HasForeignKey("RelatedMediaId");

                    b.Navigation("BOQItem");

                    b.Navigation("Creator");

                    b.Navigation("Project");

                    b.Navigation("RelatedMedia");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQMeasured", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "Item")
                        .WithOne("MeasuredData")
                        .HasForeignKey("ConstructionManagement.Domain.Entities.BOQMeasured", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQProfitabilityLog", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("ProfitabilityLogs")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOQItem");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQSupervision", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "Item")
                        .WithOne("SupervisionData")
                        .HasForeignKey("ConstructionManagement.Domain.Entities.BOQSupervision", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ClientPayment", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("ClientPayments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.EscalationLog", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("EscalationLogs")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("EscalationLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Recipient")
                        .WithMany("ReceivedEscalations")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOQItem");

                    b.Navigation("Project");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ItemDailyLog", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("DailyLogs")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ClosedByUser")
                        .WithMany("ClosedDailyLogs")
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedDailyLogs")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BOQItem");

                    b.Navigation("ClosedByUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ItemInvoice", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("Invoices")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("ItemInvoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Reviewer")
                        .WithMany("ReviewedInvoices")
                        .HasForeignKey("ReviewerUserId");

                    b.Navigation("BOQItem");

                    b.Navigation("Project");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Project", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ClosedBy")
                        .WithMany("ClosedProjects")
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "GeneralManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("GeneralManagerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedBy");

                    b.Navigation("GeneralManager");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectApprovalRule", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany()
                        .HasForeignKey("BOQItemId");

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOQItem");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRole", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRolePermission", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Permission", "Permission")
                        .WithMany("ProjectRolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.ProjectRole", "ProjectRole")
                        .WithMany("Permissions")
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("ProjectRole");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectSettings", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithOne("Settings")
                        .HasForeignKey("ConstructionManagement.Domain.Entities.ProjectSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ReportsTo")
                        .WithMany()
                        .HasForeignKey("ReportsToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ReportsTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamRole", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.ProjectRole", "ProjectRole")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.ProjectTeamMember", "ProjectTeamMember")
                        .WithMany("ProjectTeamRoles")
                        .HasForeignKey("ProjectTeamMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectRole");

                    b.Navigation("ProjectTeamMember");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.SiteMedia", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany("SiteMedias")
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("SiteMedias")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Reviewer")
                        .WithMany("ReviewedMedias")
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "Uploader")
                        .WithMany("UploadedMedias")
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BOQItem");

                    b.Navigation("Project");

                    b.Navigation("Reviewer");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.BOQItem", "BOQItem")
                        .WithMany()
                        .HasForeignKey("BOQItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedTransactions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.Project", "Project")
                        .WithMany("Transactions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "ReviewedBy")
                        .WithMany("ReviewedTransactions")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BOQItem");

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ConstructionManagement.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionManagement.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.BOQItem", b =>
                {
                    b.Navigation("DailyLogs");

                    b.Navigation("EscalationLogs");

                    b.Navigation("Invoices");

                    b.Navigation("MeasuredData");

                    b.Navigation("Notes");

                    b.Navigation("ProfitabilityLogs");

                    b.Navigation("SiteMedias");

                    b.Navigation("SupervisionData");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Permission", b =>
                {
                    b.Navigation("ProjectRolePermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Project", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("BOQItems");

                    b.Navigation("ClientPayments");

                    b.Navigation("EscalationLogs");

                    b.Navigation("ItemInvoices");

                    b.Navigation("Notes");

                    b.Navigation("ProjectRoles");

                    b.Navigation("Settings");

                    b.Navigation("SiteMedias");

                    b.Navigation("TeamMembers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectRole", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.Navigation("ProjectTeamRoles");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.SiteMedia", b =>
                {
                    b.Navigation("RelatedNotes");
                });

            modelBuilder.Entity("ConstructionManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("ClosedDailyLogs");

                    b.Navigation("ClosedProjects");

                    b.Navigation("CreatedDailyLogs");

                    b.Navigation("CreatedTransactions");

                    b.Navigation("ManagedProjects");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedProjects");

                    b.Navigation("ProjectMemberships");

                    b.Navigation("ReceivedEscalations");

                    b.Navigation("ReviewedInvoices");

                    b.Navigation("ReviewedMedias");

                    b.Navigation("ReviewedTransactions");

                    b.Navigation("UploadedMedias");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
